### Site info
title: Psychic Island
tagline: A little change of each day makes a great difference!
author: MonkCage
email: monk_lp@sina.com
baseurl: "/"
url: "https://monkcage.github.io"


### Build settings
markdown: kramdown
kramdown: 
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!--more-->

gitment:
  githubID: monkcage
  repo: monkcage.github.io
  ClientID: 3d0c8190913cd8174466
  ClientSecret: 5fba2e448e2da8566bfc8db8bd6c028e12cb98ef

theme: jekyll-theme-cayman
