### Site info
title: MonkCage's Blog
tagline: A little change of each day makes a great difference!
author: MonkCage
email: monk_lp@sina.com
baseurl: "/blog"
url: "https://monkcage.gihub.io/blog"


### Build settings
markdown: kramdown
kramdown: 
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!--more-->

theme: jekyll-theme-cayman
