### Site info
title: Psychic Island
tagline: A little change of each day makes a great difference!
author: MonkCage
email: monk_lp@sina.com
#baseurl: ""
url: "https://monkcage.github.io/"


### Build settings
markdown: kramdown
kramdown: 
        input: GFM
        syntax_highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!--more-->

gitment:
        enable: true
        repo: monkcage.github.io
        client_id: 3d0c8190913cd8174466
        client_secret: 5fba2e448e2da8566bfc8db8bd6c028e12cb98ef

theme: jekyll-theme-cayman
